FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    clang \
    g++ \
    libtool \
    libsnmp-dev \
    libxml2-dev \
    libxslt1-dev \
    make \
    nsis \
    cmake \
    git \
    qt5-qmake \
    qtbase5-dev \ 
    qt6-base-dev \
    ccache

RUN apt-get clean

WORKDIR /
CMD ["bash"]
