FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    clang \
    g++ \
    libtool \
    libsnmp-dev \
    libxml2-dev \
    libxslt1-dev \
    make \
    nsis \
    cmake \
    git \
    qt5-default \
    ccache

WORKDIR /
CMD ["bash"]
