FROM debian:bullseye AS builder
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    autopoint \
    binutils \
    bison \
    build-essential \
    bzip2 \
    cmake \
    fakeroot \
    flex \
    git \
    make \
    gperf \
    intltool \
    libgdk-pixbuf2.0-dev \
    libtool \
    libtool-bin \
    libssl-dev \
    lzip \
    python \
    python3-mako \
    p7zip-full \
    ruby \
    unzip \
    wget
WORKDIR /opt
RUN git clone https://github.com/mxe/mxe.git
# Use Qt 5.15.10
RUN cd mxe && git checkout 5f3972b4334172a9ba86e0a1b2112715fb70a680 -- src/qtbase.mk
RUN cd mxe && make MXE_TARGETS='i686-w64-mingw32.shared' -j$(nproc) qtbase libxml2 libxslt
RUN /opt/mxe/.ccache/bin/ccache -Cz

FROM debian:bullseye
RUN apt-get update && apt-get install -y nsis make git ccache
WORKDIR /
COPY --from=builder /opt/mxe /opt/mxe
CMD ["bash"]
