#ifndef INC_PIXCfgParserTokenTypes_hpp_
#define INC_PIXCfgParserTokenTypes_hpp_

/* $ANTLR 2.7.7 (20090306): "pix.g" -> "PIXCfgParserTokenTypes.hpp"$ */

#ifndef CUSTOM_API
# define CUSTOM_API
#endif

#ifdef __cplusplus
struct CUSTOM_API PIXCfgParserTokenTypes {
#endif
	enum {
		EOF_ = 1,
		NEWLINE = 4,
		IP = 5,
		QUIT = 6,
		COMMUNITY_LIST = 7,
		WORD = 8,
		CERTIFICATE = 9,
		PIX_WORD = 10,
		ASA_WORD = 11,
		VERSION_WORD = 12,
		NUMBER = 13,
		HOSTNAME = 14,
		STRING = 15,
		ACCESS_LIST = 16,
		INT_CONST = 17,
		PERMIT = 18,
		DENY = 19,
		ICMP = 20,
		TCP = 21,
		UDP = 22,
		P_EQ = 23,
		P_GT = 24,
		P_LT = 25,
		P_NEQ = 26,
		P_RANGE = 27,
		HOST = 28,
		IPV4 = 29,
		ANY = 30,
		LOG = 31,
		LOG_INPUT = 32,
		ESTABLISHED = 33,
		FRAGMENTS = 34,
		TIME_RANGE = 35,
		CONTROLLER = 36,
		INTRFACE = 37,
		VLAN = 38,
		SEC_LEVEL = 39,
		NAMEIF = 40,
		DESCRIPTION = 41,
		REMARK = 42,
		SHUTDOWN = 43,
		ADDRESS = 44,
		DHCP = 45,
		STANDBY = 46,
		SWITCHPORT = 47,
		ACCESS = 48,
		ACCESS_GROUP = 49,
		EXIT = 50,
		LINE_COMMENT = 51,
		COLON_COMMENT = 52,
		SECONDARY = 53,
		SETROUTE = 54,
		EXTENDED = 55,
		STANDARD = 56,
		Whitespace = 57,
		HEX_CONST = 58,
		NEG_INT_CONST = 59,
		DIGIT = 60,
		HEXDIGIT = 61,
		PIPE_CHAR = 62,
		NUMBER_SIGN = 63,
		PERCENT = 64,
		AMPERSAND = 65,
		APOSTROPHE = 66,
		OPENING_PAREN = 67,
		CLOSING_PAREN = 68,
		STAR = 69,
		PLUS = 70,
		COMMA = 71,
		MINUS = 72,
		DOT = 73,
		SLASH = 74,
		COLON = 75,
		SEMICOLON = 76,
		LESS_THAN = 77,
		EQUALS = 78,
		GREATER_THAN = 79,
		QUESTION = 80,
		COMMERCIAL_AT = 81,
		OPENING_SQUARE = 82,
		CLOSING_SQUARE = 83,
		CARET = 84,
		UNDERLINE = 85,
		OPENING_BRACE = 86,
		CLOSING_BRACE = 87,
		TILDE = 88,
		NULL_TREE_LOOKAHEAD = 3
	};
#ifdef __cplusplus
};
#endif
#endif /*INC_PIXCfgParserTokenTypes_hpp_*/
