#ifndef INC_PIXCfgParserTokenTypes_hpp_
#define INC_PIXCfgParserTokenTypes_hpp_

/* $ANTLR 2.7.7 (20090306): "pix.g" -> "PIXCfgParserTokenTypes.hpp"$ */

#ifndef CUSTOM_API
# define CUSTOM_API
#endif

#ifdef __cplusplus
struct CUSTOM_API PIXCfgParserTokenTypes {
#endif
	enum {
		EOF_ = 1,
		NEWLINE = 4,
		IP = 5,
		QUIT = 6,
		COMMUNITY_LIST = 7,
		NAMES = 8,
		NAME = 9,
		CRYPTO = 10,
		WORD = 11,
		CERTIFICATE = 12,
		PIX_WORD = 13,
		ASA_WORD = 14,
		VERSION_WORD = 15,
		NUMBER = 16,
		HOSTNAME = 17,
		STRING = 18,
		ACCESS_LIST = 19,
		INT_CONST = 20,
		PERMIT = 21,
		DENY = 22,
		ICMP = 23,
		TCP = 24,
		UDP = 25,
		P_EQ = 26,
		P_GT = 27,
		P_LT = 28,
		P_NEQ = 29,
		P_RANGE = 30,
		HOST = 31,
		IPV4 = 32,
		ANY = 33,
		LOG = 34,
		LOG_INPUT = 35,
		ESTABLISHED = 36,
		FRAGMENTS = 37,
		TIME_RANGE = 38,
		CONTROLLER = 39,
		INTRFACE = 40,
		VLAN = 41,
		SEC_LEVEL = 42,
		NAMEIF = 43,
		DESCRIPTION = 44,
		REMARK = 45,
		SHUTDOWN = 46,
		ADDRESS = 47,
		DHCP = 48,
		STANDBY = 49,
		SWITCHPORT = 50,
		ACCESS = 51,
		ACCESS_GROUP = 52,
		EXIT = 53,
		LINE_COMMENT = 54,
		COLON_COMMENT = 55,
		SECONDARY = 56,
		SETROUTE = 57,
		EXTENDED = 58,
		STANDARD = 59,
		Whitespace = 60,
		HEX_CONST = 61,
		NEG_INT_CONST = 62,
		DIGIT = 63,
		HEXDIGIT = 64,
		PIPE_CHAR = 65,
		NUMBER_SIGN = 66,
		PERCENT = 67,
		AMPERSAND = 68,
		APOSTROPHE = 69,
		OPENING_PAREN = 70,
		CLOSING_PAREN = 71,
		STAR = 72,
		PLUS = 73,
		COMMA = 74,
		MINUS = 75,
		DOT = 76,
		SLASH = 77,
		COLON = 78,
		SEMICOLON = 79,
		LESS_THAN = 80,
		EQUALS = 81,
		GREATER_THAN = 82,
		QUESTION = 83,
		COMMERCIAL_AT = 84,
		OPENING_SQUARE = 85,
		CLOSING_SQUARE = 86,
		CARET = 87,
		UNDERLINE = 88,
		OPENING_BRACE = 89,
		CLOSING_BRACE = 90,
		TILDE = 91,
		NULL_TREE_LOOKAHEAD = 3
	};
#ifdef __cplusplus
};
#endif
#endif /*INC_PIXCfgParserTokenTypes_hpp_*/
