#ifndef INC_PIXCfgParserTokenTypes_hpp_
#define INC_PIXCfgParserTokenTypes_hpp_

/* $ANTLR 2.7.7 (20090306): "pix.g" -> "PIXCfgParserTokenTypes.hpp"$ */

#ifndef CUSTOM_API
# define CUSTOM_API
#endif

#ifdef __cplusplus
struct CUSTOM_API PIXCfgParserTokenTypes {
#endif
	enum {
		EOF_ = 1,
		NEWLINE = 4,
		IP = 5,
		QUIT = 6,
		COMMUNITY_LIST = 7,
		WORD = 8,
		CERTIFICATE = 9,
		PIX_WORD = 10,
		ASA_WORD = 11,
		VERSION_WORD = 12,
		NUMBER = 13,
		HOSTNAME = 14,
		STRING = 15,
		ACCESS_LIST = 16,
		INT_CONST = 17,
		PERMIT = 18,
		DENY = 19,
		ICMP = 20,
		TCP = 21,
		UDP = 22,
		P_EQ = 23,
		P_GT = 24,
		P_LT = 25,
		P_NEQ = 26,
		P_RANGE = 27,
		HOST = 28,
		IPV4 = 29,
		ANY = 30,
		LOG = 31,
		LOG_INPUT = 32,
		ESTABLISHED = 33,
		FRAGMENTS = 34,
		TIME_RANGE = 35,
		CONTROLLER = 36,
		INTRFACE = 37,
		VLAN = 38,
		SEC_LEVEL = 39,
		NAMEIF = 40,
		DESCRIPTION = 41,
		REMARK = 42,
		SHUTDOWN = 43,
		ADDRESS = 44,
		DHCP = 45,
		SETROUTE = 46,
		SECONDARY = 47,
		SWITCHPORT = 48,
		ACCESS = 49,
		ACCESS_GROUP = 50,
		EXIT = 51,
		LINE_COMMENT = 52,
		COLON_COMMENT = 53,
		EXTENDED = 54,
		STANDARD = 55,
		Whitespace = 56,
		HEX_CONST = 57,
		NEG_INT_CONST = 58,
		DIGIT = 59,
		HEXDIGIT = 60,
		PIPE_CHAR = 61,
		NUMBER_SIGN = 62,
		PERCENT = 63,
		AMPERSAND = 64,
		APOSTROPHE = 65,
		OPENING_PAREN = 66,
		CLOSING_PAREN = 67,
		STAR = 68,
		PLUS = 69,
		COMMA = 70,
		MINUS = 71,
		DOT = 72,
		SLASH = 73,
		COLON = 74,
		SEMICOLON = 75,
		LESS_THAN = 76,
		EQUALS = 77,
		GREATER_THAN = 78,
		QUESTION = 79,
		COMMERCIAL_AT = 80,
		OPENING_SQUARE = 81,
		CLOSING_SQUARE = 82,
		CARET = 83,
		UNDERLINE = 84,
		OPENING_BRACE = 85,
		CLOSING_BRACE = 86,
		TILDE = 87,
		NULL_TREE_LOOKAHEAD = 3
	};
#ifdef __cplusplus
};
#endif
#endif /*INC_PIXCfgParserTokenTypes_hpp_*/
